// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketfy.Data;

#nullable disable

namespace Ticketfy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801054956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Ticketfy.Data.Entities.AttendanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("RutaFotoEvidencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("ruta_foto_evidencia");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_movimiento");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_attendances_user");

                    b.ToTable("asistencias");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Meta")
                        .HasColumnType("TEXT")
                        .HasColumnName("meta");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CoOccurrenceEntity", b =>
                {
                    b.Property<string>("ProductoA")
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_a");

                    b.Property<string>("ProductoB")
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_b");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frecuencia");

                    b.HasKey("ProductoA", "ProductoB");

                    b.ToTable("co_ocurrencia");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Debt")
                        .HasColumnType("REAL")
                        .HasColumnName("debt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<double>("PuntosSaldo")
                        .HasColumnType("REAL")
                        .HasColumnName("puntos_saldo");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerPaymentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("customerId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_customer_payments_customer");

                    b.ToTable("customer_payments");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.FiscalClientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rfc");

                    b.Property<string>("UsoCfdi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uso_cfdi");

                    b.HasKey("Id");

                    b.ToTable("clientes_fiscales");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ParkedOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("parked_orders");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL")
                        .HasColumnName("cost");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpiresSoon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expiresSoon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<double>("Stock")
                        .HasColumnType("REAL")
                        .HasColumnName("stock");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<double>("WholesalePrice")
                        .HasColumnType("REAL")
                        .HasColumnName("wholesalePrice");

                    b.Property<int>("WholesaleThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wholesaleThreshold");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("idx_products_barcode");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_products_category");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.PromotionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BuyQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buyQty");

                    b.Property<string>("DiscountType")
                        .HasColumnType("TEXT")
                        .HasColumnName("discountType");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("REAL")
                        .HasColumnName("discountValue");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PayQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payQty");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("targetId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SaleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelledAt");

                    b.Property<double>("ChangeAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("changeAmount");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customerId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("EstadoFiscal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_fiscal");

                    b.Property<int>("IsCancelled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isCancelled");

                    b.Property<int>("IsCredit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isCredit");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("paidAmount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("paymentMethod");

                    b.Property<double>("Profit")
                        .HasColumnType("REAL")
                        .HasColumnName("profit");

                    b.Property<string>("SerieFolio")
                        .HasColumnType("TEXT")
                        .HasColumnName("serie_folio");

                    b.Property<double>("Total")
                        .HasColumnType("REAL")
                        .HasColumnName("total");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCost");

                    b.Property<string>("UuidSat")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid_sat");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_sales_customer");

                    b.HasIndex("Date")
                        .HasDatabaseName("idx_sales_date");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ShiftEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("ActualBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("actualBalance");

                    b.Property<double?>("Diff")
                        .HasColumnType("REAL")
                        .HasColumnName("diff");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endTime");

                    b.Property<double>("ExpectedBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("expectedBalance");

                    b.Property<int>("IsOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isOpen");

                    b.Property<double>("OpeningBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("openingBalance");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("startTime");

                    b.Property<double>("TotalCashSales")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCashSales");

                    b.Property<double>("TotalCreditSales")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCreditSales");

                    b.HasKey("Id");

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Estatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PinChecadorHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("pin_checador_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.AttendanceEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.UserEntity", "Usuario")
                        .WithMany("Attendances")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerPaymentEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.FiscalClientEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.CustomerEntity", "Customer")
                        .WithOne("FiscalData")
                        .HasForeignKey("Ticketfy.Data.Entities.FiscalClientEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerEntity", b =>
                {
                    b.Navigation("FiscalData");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
