// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketfy.Data;

#nullable disable

namespace Ticketfy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Ticketfy.Data.Entities.AttendanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_out_time");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asistencias");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CashupEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("ClosedCashAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("closed_cash_amount");

                    b.Property<int>("Count050")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_050");

                    b.Property<int>("Count1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_1");

                    b.Property<int>("Count10")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_10");

                    b.Property<int>("Count100")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_100");

                    b.Property<int>("Count1000")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_1000");

                    b.Property<int>("Count2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_2");

                    b.Property<int>("Count20")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_20");

                    b.Property<int>("Count200")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_200");

                    b.Property<int>("Count5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_5");

                    b.Property<int>("Count50")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_50");

                    b.Property<int>("Count500")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count_500");

                    b.Property<double>("Difference")
                        .HasColumnType("REAL")
                        .HasColumnName("difference");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<double>("OpenCashAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("open_cash_amount");

                    b.Property<string>("ShiftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shift_id");

                    b.Property<double>("TheoreticalCash")
                        .HasColumnType("REAL")
                        .HasColumnName("theoretical_cash");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("cashups");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CoOccurrenceEntity", b =>
                {
                    b.Property<string>("ProductoA")
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_a");

                    b.Property<string>("ProductoB")
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_b");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frecuencia");

                    b.HasKey("ProductoA", "ProductoB");

                    b.ToTable("co_ocurrencia");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<double>("CreditLimit")
                        .HasColumnType("REAL")
                        .HasColumnName("credit_limit");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_code");

                    b.Property<double>("Debt")
                        .HasColumnType("REAL")
                        .HasColumnName("debt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsCreditBlocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_credit_blocked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<double>("PuntosSaldo")
                        .HasColumnType("REAL")
                        .HasColumnName("puntos_saldo");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rfc");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerPaymentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("customerId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ShiftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shift_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShiftId");

                    b.ToTable("customer_payments");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ExpenseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredByUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.FiscalClientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rfc");

                    b.Property<string>("UsoCfdi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uso_cfdi");

                    b.HasKey("Id");

                    b.ToTable("clientes_fiscales");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.FolioSequenceEntity", b =>
                {
                    b.Property<string>("DatePrefix")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("DatePrefix");

                    b.ToTable("FolioSequences");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.GiftcardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL")
                        .HasColumnName("balance");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("card_number");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("giftcards");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.InventorySnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventorySnapshots");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.InventorySnapshotItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CostPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellingPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("InventorySnapshotItems");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ItemKitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("KitBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kit_barcode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_product_id");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductId");

                    b.ToTable("item_kits");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ItemKitItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ItemKitId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_kit_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ItemKitId");

                    b.HasIndex("ProductId");

                    b.ToTable("item_kit_items");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ParkedOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("parked_orders");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ProductAttributeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attribute_name");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attribute_value");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.ToTable("product_attributes");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL")
                        .HasColumnName("cost");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultSupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_supplier_id");

                    b.Property<int>("ExpiresSoon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expiresSoon");

                    b.Property<bool>("IsKit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_kit");

                    b.Property<string>("LocationRack")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location_rack");

                    b.Property<double>("MinStock")
                        .HasColumnType("REAL")
                        .HasColumnName("minStock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("PointsRewarded")
                        .HasColumnType("REAL")
                        .HasColumnName("points_rewarded");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<double>("ReorderQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("reorder_quantity");

                    b.Property<string>("SatProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sat_product_code");

                    b.Property<string>("SatUnitCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sat_unit_code");

                    b.Property<double>("Stock")
                        .IsConcurrencyToken()
                        .HasColumnType("REAL")
                        .HasColumnName("stock");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<double>("WholesalePrice")
                        .HasColumnType("REAL")
                        .HasColumnName("wholesalePrice");

                    b.Property<int>("WholesaleThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wholesaleThreshold");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSupplierId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.PromotionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BuyQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buyQty");

                    b.Property<string>("DiscountType")
                        .HasColumnType("TEXT")
                        .HasColumnName("discountType");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("REAL")
                        .HasColumnName("discountValue");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<double>("FreeQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("free_quantity");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<double>("MinQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PayQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payQty");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<int>("StrategyType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strategy_type");

                    b.Property<string>("TargetCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_category");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("targetId");

                    b.Property<string>("TargetProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_product_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.PurchaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.PurchaseItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ReturnEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CashierUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cashier_user_id");

                    b.Property<double>("CogsReversed")
                        .HasColumnType("REAL")
                        .HasColumnName("cogs_reversed");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalSaleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_sale_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("refund_method");

                    b.Property<double>("TotalRefunded")
                        .HasColumnType("REAL")
                        .HasColumnName("total_refunded");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSaleId");

                    b.ToTable("returns");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SaleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CancellationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelledAt");

                    b.Property<double>("ChangeAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("changeAmount");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customerId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("EstadoFiscal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_fiscal");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_status");

                    b.Property<int>("IsCancelled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isCancelled");

                    b.Property<int>("IsCredit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isCredit");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("paidAmount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("paymentMethod");

                    b.Property<double>("Profit")
                        .HasColumnType("REAL")
                        .HasColumnName("profit");

                    b.Property<string>("SerieFolio")
                        .HasColumnType("TEXT")
                        .HasColumnName("serie_folio");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<double>("Total")
                        .HasColumnType("REAL")
                        .HasColumnName("total");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCost");

                    b.Property<string>("UuidSat")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid_sat");

                    b.HasKey("Id");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ShiftEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("ActualBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("actualBalance");

                    b.Property<double?>("Diff")
                        .HasColumnType("REAL")
                        .HasColumnName("diff");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endTime");

                    b.Property<double>("ExpectedBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("expectedBalance");

                    b.Property<int>("IsOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isOpen");

                    b.Property<double>("OpeningBalance")
                        .HasColumnType("REAL")
                        .HasColumnName("openingBalance");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("startTime");

                    b.Property<double>("TotalCashSales")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCashSales");

                    b.Property<double>("TotalCreditSales")
                        .HasColumnType("REAL")
                        .HasColumnName("totalCreditSales");

                    b.HasKey("Id");

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ShiftMovementEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsOutflow")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_outflow");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movement_type");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift_id");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("shift_movements");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ShiftNoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cashier_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_resolved");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("note_text");

                    b.HasKey("Id");

                    b.ToTable("shift_notes");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SupplierEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SystemAlertEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("SupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("system_alerts");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estatus");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordHashBytes")
                        .HasColumnType("BLOB")
                        .HasColumnName("password_hash_bytes");

                    b.Property<string>("PasswordHint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hint");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB")
                        .HasColumnName("password_salt");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pin_checador_hash");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.AttendanceEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.UserEntity", "Usuario")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerPaymentEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketfy.Data.Entities.ShiftEntity", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Customer");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.FiscalClientEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.CustomerEntity", "Customer")
                        .WithOne("FiscalData")
                        .HasForeignKey("Ticketfy.Data.Entities.FiscalClientEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.InventorySnapshotItemEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.InventorySnapshotEntity", "Snapshot")
                        .WithMany("Items")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ItemKitEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.ProductEntity", "ParentProduct")
                        .WithMany()
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ItemKitItemEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.ItemKitEntity", "ItemKit")
                        .WithMany("Components")
                        .HasForeignKey("ItemKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketfy.Data.Entities.ProductEntity", "IngredientProduct")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientProduct");

                    b.Navigation("ItemKit");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.SupplierEntity", "DefaultSupplier")
                        .WithMany()
                        .HasForeignKey("DefaultSupplierId");

                    b.Navigation("DefaultSupplier");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ReturnEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.SaleEntity", "OriginalSale")
                        .WithMany()
                        .HasForeignKey("OriginalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalSale");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ShiftMovementEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.ShiftEntity", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.SystemAlertEntity", b =>
                {
                    b.HasOne("Ticketfy.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Ticketfy.Data.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.CustomerEntity", b =>
                {
                    b.Navigation("FiscalData");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.InventorySnapshotEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.ItemKitEntity", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Ticketfy.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
